attn_spectrogram:
  _target_: memory_policy.AttentionSpectrogram
  per_layer: ${per_layer}
  per_head: ${per_head}
  shared: ${embedding_shared}
  output_params: ${embedding_output_params}
  stft_params: ${stft_params}

embedding_output_params:
  _target_: memory_policy.ComponentOutputParams
  requires_recomputation: ${embedding_requires_recomputation}
  reduction_mode: ${embedding_reduction_mode}
  ema_params: ${embedding_ema_params}
  output_past_non_reduced_history: ${embedding_output_past_non_reduced_history}
  max_non_reduced_history_len: ${embedding_max_non_reduced_history_len}

embedding_ema_params:
  _target_: memory_policy.EMAParams
  coeff: ${embedding_ema_coeff}
  learned: ${embedding_reduction_learned}
  reduction_stride: ${hop_length}

stft_params:
  _target_: memory_policy.STFTParams
  n_fft: ${n_fft}
  hop_length: ${hop_length}
  window_fn: ${window_fn}
  pad_mode: ${pad_mode}
  output_magnitudes: ${output_magnitudes}

# Spectrogram params.
embedding_shared: true
# Output params.
embedding_requires_recomputation: true
embedding_reduction_mode:
# Ema params.
embedding_ema_coeff: 0.975
embedding_reduction_learned: false
# --
embedding_output_past_non_reduced_history: false
embedding_max_non_reduced_history_len:
# --
# Stft params
n_fft: 32
hop_length: 16
window_fn:
  _target_: memory_policy.fft_avg_mask
  window_length: ${n_fft}
pad_mode: constant
output_magnitudes: true
# --

window_fn_log_name: avg
embedding_spec_mp_log_name: attn-spec